# Generated by Django 4.1.5 on 2023-01-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
