# Generated by Django 4.1.4 on 2022-12-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_student_options_student_about_student_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='studen_files'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student'),
        ),
    ]
