# Generated by Django 4.1.4 on 2022-12-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_student_files_alter_student_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='student_files'),
        ),
    ]
